---
title: AI Bot for MKT 562
author: Mike Nguyen
date: '2023-08-09'
slug: ai-bot-for-mkt-562
categories:
  - teaching
tags:
  - Academic
subtitle: ''
summary: ''
authors: []
lastmod: '2023-08-09T13:37:48-07:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

**Welcome to Advertising and Social Media - MKT 526**

This page gives you a quick way to ask all questions related to the class syllabus.

**What is it?** AdBot is an AI-powered Teaching Assistant (TA) bot, specifically designed to support students in the Advertising and Social Media class. Whether you have questions about advertising campaigns, social media trends, or digital marketing strategies, AdBot is here to provide insights and answers.

**Disclaimer**: AdBot is a cutting-edge tool developed quickly for educational purposes using advanced AI technologies. Please refrain from sharing personal or sensitive information with it.

**Here are some sample questions you can ask AdBot:**

**Course Logistics:**

-   What are the grading criteria for the group project?

-   When is the deadline for our group project proposal?

-   Can you show me the schedule for guest lectures?

**Language Options:**

-   Feel free to ask questions in any language, and AdBot will reply in the language of your question.

**Feedback and Comments:**

-   Please direct any comments or suggestions to your course teaching assistant's email.

If you can't see the widget, please access via this [url](https://widget.getcody.ai/99d9d523-c1dd-4c06-8823-176c69f39d4c)

## AI Teaching Assistant

<iframe src="https://widget.getcody.ai/99d9d523-c1dd-4c06-8823-176c69f39d4c" style="border:0px;" name="codyai" scrolling="no" frameborder="1" marginheight="0" marginwidth="0" height="800px" width="100%" allowfullscreen>

</iframe>
